/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package register;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class Register extends javax.swing.JFrame {
private static final String USERNAMEE= "u572797458_soft";
private static final String PASSWORDD= "password0880";
private static final String CONN_STRING="jdbc:mysql://db144.hostinger.in.th/u572797458_soft";
    /**
     * Creates new form NewJFrame
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        register1 = new register.Main();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Usernamefield = new javax.swing.JTextField();
        Repasswordfield = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        Passwordfield = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        Clear = new javax.swing.JButton();
        Register1 = new javax.swing.JButton();
        Register = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 168, 1));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 1200));
        jPanel1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setSize(new java.awt.Dimension(1200, 1200));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(239, 87, 119));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 10, 310, 110);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1030, 130);

        jPanel3.setBackground(new java.awt.Color(75, 207, 250));
        jPanel3.setLayout(null);

        Usernamefield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Usernamefield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        Usernamefield.setOpaque(false);
        Usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamefieldActionPerformed(evt);
            }
        });
        jPanel3.add(Usernamefield);
        Usernamefield.setBounds(550, 180, 460, 40);

        Repasswordfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Repasswordfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        Repasswordfield.setOpaque(false);
        Repasswordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepasswordfieldActionPerformed(evt);
            }
        });
        jPanel3.add(Repasswordfield);
        Repasswordfield.setBounds(550, 460, 460, 50);

        jPanel5.setBackground(new java.awt.Color(255, 63, 52));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, -40, 1040, 100);

        Passwordfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Passwordfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        Passwordfield.setOpaque(false);
        Passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordfieldActionPerformed(evt);
            }
        });
        jPanel3.add(Passwordfield);
        Passwordfield.setBounds(550, 300, 460, 50);

        jPanel6.setBackground(new java.awt.Color(255, 221, 89));
        jPanel6.setLayout(null);

        Clear.setBackground(new java.awt.Color(245, 59, 87));
        Clear.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel6.add(Clear);
        Clear.setBounds(420, 50, 216, 90);

        Register1.setBackground(new java.awt.Color(5, 196, 107));
        Register1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Register1.setText("Back");
        Register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register1ActionPerformed(evt);
            }
        });
        jPanel6.add(Register1);
        Register1.setBounds(160, 50, 216, 90);

        Register.setBackground(new java.awt.Color(5, 196, 107));
        Register.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel6.add(Register);
        Register.setBounds(700, 50, 216, 90);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(-10, 660, 1040, 180);

        jPanel4.setBackground(new java.awt.Color(15, 188, 249));
        jPanel4.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register/register.png"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(30, 110, 450, 498);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 480, 850);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Re-Password");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(480, 380, 310, 70);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Username");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(480, 110, 220, 70);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Password");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(480, 250, 220, 70);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 140, 1030, 860);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernamefieldActionPerformed

    private void RepasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepasswordfieldActionPerformed

    private void PasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordfieldActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
       Usernamefield.setText("");
       Passwordfield.setText(""); 
       Repasswordfield.setText("");
       // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
            PreparedStatement pst;

                if(Usernamefield.getText().equals("")||
                        new String(Passwordfield.getPassword()).equals("")||
                        new String(Repasswordfield.getPassword()).equals("")){
                    JOptionPane.showMessageDialog(null,"กรุณากรอกข้อมูลให้ครบ !");
                }else{
                    if( new String(Passwordfield.getPassword()).equals( new String(Repasswordfield.getPassword()))){

                        try{
                             String serverName = "db144.hostinger.in.th";
                             String mydatabase = "u572797458_soft";
                             String url = "jdbc:mysql://" + serverName + "/" + mydatabase;
                             String username = "u572797458_soft";
                             String password = "password0880";
                             Connection connection = DriverManager.getConnection(url, username, password);
                             connection.createStatement();
//เช็คว่ามี user นี้หรือยัง
                            String CheckUser=Usernamefield.getText();
                            String sql="SELECT Username FROM u572797458_soft.Username where Username=?";
                            pst=connection.prepareStatement(sql);
                            pst.setString(1,CheckUser);
                            ResultSet rs = pst.executeQuery();

///

                            boolean russ=rs.next();
                            if(russ==true){
                                System.out.println("regi5555");
                                JOptionPane.showMessageDialog(null,"มี User ซ้ำ");
                            }else {
                                InsertUser();
                            }


                        }

                        catch(Exception String) {
                            JOptionPane.showMessageDialog(null,String);

                        }


                    }
                    else{
                        JOptionPane.showMessageDialog(null, "รหัสผ่านไม่ตรงกัน");

                    }
                }


       
    LoginForm go = new  LoginForm();
    go.setVisible(true);
    setVisible(false);
    }//GEN-LAST:event_RegisterActionPerformed

    private void Register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register1ActionPerformed
       
        
        new LoginForm().setVisible(true);
      this.dispose();   
    }//GEN-LAST:event_Register1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JPasswordField Passwordfield;
    private javax.swing.JButton Register;
    private javax.swing.JButton Register1;
    private javax.swing.JPasswordField Repasswordfield;
    private javax.swing.JTextField Usernamefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private register.Main register1;
    // End of variables declaration//GEN-END:variables

    private void InsertUser() {
        PreparedStatement pst;
        try {
            String serverName = "db144.hostinger.in.th";
            String mydatabase = "u572797458_soft";
            String url = "jdbc:mysql://" + serverName + "/" + mydatabase;
            String username = "u572797458_soft";
            String password = "password0880";
            Connection connection = DriverManager.getConnection(url, username, password);
            connection.createStatement();

            String sql ="Insert into Username(Username,Password) values (?,?)";

            pst=connection.prepareStatement(sql);
            pst.setString(1, Usernamefield.getText());
            pst.setString(2,  new String(Passwordfield.getPassword()));
            pst.execute();
            JOptionPane.showMessageDialog(null,"finish");
            Usernamefield.setText("");
            Passwordfield.setText("");
            Repasswordfield.setText("");
            
            
        }catch (Exception String){

        }


 //To change body of generated methods, choose Tools | Templates.
    }
}
