/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package register;

/**
 *
 * @author Admin
 */
public class room1 extends javax.swing.JFrame {

    /**
     * Creates new form room1
     */
    public room1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ccbtn = new javax.swing.JButton();
        createbtn = new javax.swing.JButton();
        Passwordfield = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        nameroom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(802, 516));
        setPreferredSize(new java.awt.Dimension(802, 516));
        getContentPane().setLayout(null);

        ccbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ccbtn.setText("Cancal");
        getContentPane().add(ccbtn);
        ccbtn.setBounds(490, 380, 180, 60);

        createbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createbtn.setText("Creat Room");
        getContentPane().add(createbtn);
        createbtn.setBounds(190, 380, 180, 60);

        Passwordfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Passwordfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        Passwordfield.setOpaque(false);
        Passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordfieldActionPerformed(evt);
            }
        });
        getContentPane().add(Passwordfield);
        Passwordfield.setBounds(350, 220, 340, 50);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setText("Lock Room");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(350, 290, 140, 40);

        nameroom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nameroom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        nameroom.setOpaque(false);
        nameroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameroomActionPerformed(evt);
            }
        });
        getContentPane().add(nameroom);
        nameroom.setBounds(350, 150, 340, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("Password     :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 200, 250, 100);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Name Room :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 120, 250, 100);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Create Room");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 20, 300, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register/tumblr_oiwyturZ9q1tf8vylo1_1280.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 520);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Name Room :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 120, 250, 100);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameroomActionPerformed

    private void PasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new room1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Passwordfield;
    private javax.swing.JButton ccbtn;
    private javax.swing.JButton createbtn;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameroom;
    // End of variables declaration//GEN-END:variables
}
